org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=768m -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configureondemand=true
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx1024M
file.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
