// File generated by the FlutterFire CLI.
// https://github.com/firebase/flutterfire_cli

import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8bIm1xmhuXlXm5OozVpFP69TkOvOn_T4',
    appId: '1:515859666283:android:8bb29a45bb352c8de1a82e',
    messagingSenderId: '515859666283',
    projectId: 'zenfoo-4860d',
    storageBucket: 'zenfoo-4860d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlgsrylKp5p8S_5MUAi6eETNs71e-yRiU',
    appId: '1:515859666283:ios:75f8014114cc8dc2e1a82e',
    messagingSenderId: '515859666283',
    projectId: 'zenfoo-4860d',
    storageBucket: 'zenfoo-4860d.firebasestorage.app',
    iosBundleId: 'com.zenfoo.partner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8bIm1xmhuXlXm5OozVpFP69TkOvOn_T4',
    appId: '1:515859666283:web:your-web-app-id',
    messagingSenderId: '515859666283',
    projectId: 'zenfoo-4860d',
    storageBucket: 'zenfoo-4860d.firebasestorage.app',
  );
}
